### ISSUE TITLE
Can i use some audio assets?

### ISSUE THREAD

**Issue by Specy** [McbeEringi/mcbeeringi.github.io#1]
Hi!

I wanted to ask if i could use some of your audio assets, i only have the piano and harp in my account and can't get many others, so i was asking if i could get some of the ones you are using.

Thanks!

**Comment by tracey-le** [comment]
I think they’re taken from Sky internally (which might be against Terms of Service) The quena, contrabass are internal names used in the game

https://thatgamecompany.helpshift.com/a/sky-children-of-the-light/?s=legal&f=eula-terms-of-service&l=en

> You may not modify, distribute, transmit, display, perform, reproduce (except for one archival and backup copy as permitted by applicable laws), publish, license, create derivative works from, adapt, translate, sublicense, auction, rent, lease or sell all or any part of the Game. In addition, you may not hack, emulate, reverse engineer, decompile, or disassemble any part of the Game.  All rights not expressly granted are reserved by us. You agree that you have no interest, monetary or otherwise, in any feature, content, or Intellectual Property contained in the Game;

> You may not modify or cause to be modified any files that are a part of the Game in any way not expressly authorized by us;

**Comment by Specy** [comment]
Hey Tracey!
I will "analize" tomorrow if they were ripped or recorded, or maybe we get an answer

**Comment by McbeEringi** [comment]
I checked the official website, and realize it was against the user agreement.
I'm sorry.
I'll delete audio assets.

**Comment by tracey-le** [comment]
Aw that’s ok
