### ISSUE TITLE
Prevent Glyph generator from adding unused glyphs

### ISSUE THREAD

**Issue by RaXorX** [McbeEringi/mcbeeringi.github.io#2]
Glyph generator when used to create custom fonts adds in additional unused glyphs not present in the font nor does the game uses them either. For example, it adds in glyphs for Chinese, Japanese, Hindi etc etc languages for one, which are never used within the game. 

Is there a way to prevent that from happening? It seems like it's copying/adding in the glyphs from somewhere else, since the OG font didn't include those glyphs, they look nothing like the font at all. This unintentionally increases the size of the font when it doesn't need to be that much.

**Comment by McbeEringi** [comment]
There is a setting section defines which file to export.

- "list mode" check box
  - checked: exports files **not** defined in "list" section
  - unchecked: exports files defined in "list" section
- "list" defines files
   syntax: `<index>||<rangedIndex>, ...`
    - \<index>: "glyph_XX.png" XX part
    - \<rangedIndex>: shorthand of <index> 
       syntax: `<index>~<index>`

if you want only glyph_00 and default8 files,
check in the list mode checkbox
and input the "00" in the list box.
