### ISSUE TITLE
Having error with GitDir

### ISSUE THREAD

**Issue by tutinoko2048** [McbeEringi/mcbeeringi.github.io#6]
ReferenceError: Can't find variable: zip
59行目でエラーが出ているようです。直してくださるとありがたいです！

https://github.com/McbeEringi/mcbeeringi.github.io/blob/3d09a2be9ee96da0b0e3a6456d87632477a81f78/apps/gitdir.html#L59

**Comment by McbeEringi** [comment]
報告ありがとうございます
修正しました
https://github.com/McbeEringi/mcbeeringi.github.io/commit/f8d6084028f197cecd5e34fa53a6975e5e6983e7
